export const systemRoleDefinitions = [
  {
    key: 'owner',
    name: 'Owner',
    description: 'Full tenant control',
    permissions: [
      'extensions.read',
      'extensions.manage',
      'workspace.read',
      'workspace.create',
      'workspace.update',
      'workspace.delete',
      'member.read',
      'member.add',
      'member.update',
      'member.remove',
      'user.read',
      'user.create',
      'user.update',
      'user.disable',
      'user.remove',
      'role.read',
      'role.create',
      'role.update',
      'role.delete',
      'role.assign',
      'page.read',
      'page.create',
      'page.update',
      'page.delete',
      'page.publish',
      'page.rollback',
      'lead.read',
      'lead.update',
      'analytics.read',
      'integration.read',
      'integration.create',
      'integration.update',
      'integration.delete',
      'integration.delivery.read',
      'integration.delivery.retry',
      'domain.read',
      'domain.create',
      'domain.update',
      'domain.delete',
      'domain.verify',
      'seo.read',
      'seo.update',
      'billing.read',
      'audit.read',
      'site.read',
      'site.create',
      'site.update',
      'asset.read',
      'asset.create',
      'asset.delete',
      'template.read',
      'template.create',
      'template.update',
      'template.delete',
      'reusable.read',
      'reusable.create',
      'reusable.update',
      'reusable.delete',
      'design-system.read',
      'design-system.update',
      'form-integration.read',
      'form-integration.update',
      'workflow.read',
      'workflow.create',
      'workflow.update',
      'workflow.publish',
      'workflow.enable',
      'workflow.disable',
      'workflow.execution.read',
      'workflow.execution.retry',
    ],
  },
  {
    key: 'admin',
    name: 'Admin',
    description: 'Operational tenant administration',
    permissions: [
      'extensions.read',
      'extensions.manage',
      'workspace.read',
      'workspace.create',
      'workspace.update',
      'member.read',
      'member.add',
      'member.update',
      'member.remove',
      'user.read',
      'user.create',
      'user.update',
      'user.disable',
      'user.remove',
      'role.read',
      'role.create',
      'role.update',
      'role.delete',
      'role.assign',
      'page.read',
      'page.create',
      'page.update',
      'page.delete',
      'page.publish',
      'page.rollback',
      'lead.read',
      'lead.update',
      'analytics.read',
      'integration.read',
      'integration.create',
      'integration.update',
      'integration.delete',
      'integration.delivery.read',
      'integration.delivery.retry',
      'domain.read',
      'domain.create',
      'domain.update',
      'domain.delete',
      'domain.verify',
      'seo.read',
      'seo.update',
      'billing.read',
      'audit.read',
      'site.read',
      'site.create',
      'site.update',
      'asset.read',
      'asset.create',
      'asset.delete',
      'template.read',
      'template.create',
      'template.update',
      'template.delete',
      'reusable.read',
      'reusable.create',
      'reusable.update',
      'reusable.delete',
      'design-system.read',
      'design-system.update',
      'form-integration.read',
      'form-integration.update',
      'workflow.read',
      'workflow.create',
      'workflow.update',
      'workflow.publish',
      'workflow.enable',
      'workflow.disable',
      'workflow.execution.read',
      'workflow.execution.retry',
    ],
  },
  {
    key: 'editor',
    name: 'Editor',
    description: 'Content editing without publishing',
    permissions: [
      'workspace.read',
      'page.read',
      'page.create',
      'page.update',
      'lead.read',
      'analytics.read',
      'integration.read',
      'domain.read',
      'seo.read',
      'seo.update',
      'site.read',
      'site.create',
      'site.update',
      'asset.read',
      'asset.create',
      'template.read',
      'template.create',
      'template.update',
      'reusable.read',
      'reusable.create',
      'reusable.update',
      'design-system.read',
      'design-system.update',
      'form-integration.read',
      'workflow.read',
      'workflow.create',
      'workflow.update',
      'workflow.execution.read',
    ],
  },
  {
    key: 'viewer',
    name: 'Viewer',
    description: 'Read-only tenant access',
    permissions: [
      'workspace.read',
      'page.read',
      'analytics.read',
      'seo.read',
      'site.read',
      'asset.read',
      'template.read',
      'reusable.read',
      'design-system.read',
      'workflow.read',
      'workflow.execution.read',
    ],
  },
] as const;

export const legacyRoleKeys = {
  owner: 'owner',
  admin: 'admin',
  member: 'editor',
} as const;
