import { theme as antdTheme, type MappingAlgorithm, type ThemeConfig } from 'antd';

type AdminThemeMode = 'dark' | 'light';
type AdminSemanticColorTokens = NonNullable<ThemeConfig['token']>;

const adminSemanticColorTokens: AdminSemanticColorTokens = {
  colorPrimary: 'var(--cms-primary)',
  colorPrimaryBg: 'var(--cms-primary-muted)',
  colorPrimaryBgHover: 'var(--cms-primary-glow)',
  colorPrimaryBorder: 'var(--cms-border-default)',
  colorPrimaryBorderHover: 'var(--cms-border-hover)',
  colorPrimaryHover: 'var(--cms-primary-hover)',
  colorPrimaryActive: 'var(--cms-primary)',
  colorPrimaryTextHover: 'var(--cms-primary-hover)',
  colorPrimaryText: 'var(--cms-primary)',
  colorPrimaryTextActive: 'var(--cms-primary)',
  colorSuccessBg: 'var(--cms-success-surface)',
  colorSuccessBgHover: 'var(--cms-success-surface)',
  colorSuccessBorder: 'var(--cms-success)',
  colorSuccessBorderHover: 'var(--cms-success)',
  colorSuccessHover: 'var(--cms-success)',
  colorSuccess: 'var(--cms-success)',
  colorSuccessActive: 'var(--cms-success)',
  colorSuccessTextHover: 'var(--cms-success)',
  colorSuccessText: 'var(--cms-success)',
  colorSuccessTextActive: 'var(--cms-success)',
  colorWarningBg: 'var(--cms-warning-surface)',
  colorWarningBgHover: 'var(--cms-warning-surface)',
  colorWarningBorder: 'var(--cms-warning-border)',
  colorWarningBorderHover: 'var(--cms-warning)',
  colorWarningHover: 'var(--cms-warning)',
  colorWarning: 'var(--cms-warning)',
  colorWarningActive: 'var(--cms-warning)',
  colorWarningTextHover: 'var(--cms-warning-text)',
  colorWarningText: 'var(--cms-warning-text)',
  colorWarningTextActive: 'var(--cms-warning-text)',
  colorInfoBg: 'var(--cms-info-surface)',
  colorInfoBgHover: 'var(--cms-info-surface)',
  colorInfoBorder: 'var(--cms-info)',
  colorInfoBorderHover: 'var(--cms-info)',
  colorInfoHover: 'var(--cms-info)',
  colorInfo: 'var(--cms-info)',
  colorInfoActive: 'var(--cms-info)',
  colorInfoTextHover: 'var(--cms-info)',
  colorInfoText: 'var(--cms-info)',
  colorInfoTextActive: 'var(--cms-info)',
  colorErrorBg: 'var(--cms-danger-surface)',
  colorErrorBgHover: 'var(--cms-danger-muted)',
  colorErrorBgFilledHover: 'var(--cms-danger-muted)',
  colorErrorBgActive: 'var(--cms-danger-muted)',
  colorErrorBorder: 'var(--cms-danger-border)',
  colorErrorBorderHover: 'var(--cms-danger)',
  colorErrorHover: 'var(--cms-danger)',
  colorError: 'var(--cms-danger)',
  colorErrorActive: 'var(--cms-danger)',
  colorErrorTextHover: 'var(--cms-danger)',
  colorErrorText: 'var(--cms-danger)',
  colorErrorTextActive: 'var(--cms-danger)',
  colorText: 'var(--cms-text-primary)',
  colorTextSecondary: 'var(--cms-text-secondary)',
  colorTextTertiary: 'var(--cms-text-muted)',
  colorTextQuaternary: 'var(--cms-text-disabled)',
  colorBorder: 'var(--cms-border-default)',
  colorBorderSecondary: 'var(--cms-border-default)',
  colorBorderDisabled: 'var(--cms-border-default)',
  colorFill: 'var(--cms-bg-surface-selected)',
  colorFillSecondary: 'var(--cms-bg-surface-hover)',
  colorFillTertiary: 'var(--cms-bg-surface-muted)',
  colorFillQuaternary: 'var(--cms-bg-surface-muted)',
  colorBgLayout: 'var(--cms-bg-canvas)',
  colorBgContainer: 'var(--cms-bg-surface)',
  colorBgElevated: 'var(--cms-bg-surface-raised)',
  colorBgSpotlight: 'var(--cms-bg-surface-selected)',
  colorBgBlur: 'var(--cms-bg-overlay)',
  colorBgSolid: 'var(--cms-bg-surface-raised)',
  colorBgSolidActive: 'var(--cms-bg-surface-selected)',
  colorBgSolidHover: 'var(--cms-bg-surface-hover)',
  colorBgMask: 'var(--cms-bg-overlay)',
  colorWhite: 'var(--cms-text-inverse)',
  colorLink: 'var(--cms-info)',
  colorLinkHover: 'var(--cms-primary-hover)',
  colorLinkActive: 'var(--cms-primary)',
  colorFillContentHover: 'var(--cms-bg-surface-hover)',
  colorFillAlter: 'var(--cms-bg-surface-muted)',
  colorFillContent: 'var(--cms-bg-surface)',
  colorBgContainerDisabled: 'var(--cms-bg-control)',
  colorBgTextHover: 'var(--cms-bg-surface-hover)',
  colorBgTextActive: 'var(--cms-bg-surface-selected)',
  colorBorderBg: 'var(--cms-border-default)',
  colorSplit: 'var(--cms-border-default)',
  colorTextPlaceholder: 'var(--cms-text-muted)',
  colorTextDisabled: 'var(--cms-text-disabled)',
  colorTextHeading: 'var(--cms-text-primary)',
  colorTextLabel: 'var(--cms-text-secondary)',
  colorTextDescription: 'var(--cms-text-muted)',
  colorTextLightSolid: 'var(--cms-text-inverse)',
  colorIcon: 'var(--cms-text-muted)',
  colorIconHover: 'var(--cms-text-primary)',
  colorHighlight: 'var(--cms-primary-muted)',
  controlOutline: 'var(--cms-primary-glow)',
  colorWarningOutline: 'var(--cms-warning-border)',
  colorErrorOutline: 'var(--cms-danger-border)',
  colorErrorAffix: 'var(--cms-danger)',
  colorWarningAffix: 'var(--cms-warning)',
  controlItemBgHover: 'var(--cms-bg-surface-hover)',
  controlItemBgActive: 'var(--cms-bg-surface-selected)',
  controlItemBgActiveHover: 'var(--cms-bg-surface-selected)',
  controlItemBgActiveDisabled: 'var(--cms-bg-surface-muted)',
};

const adminMappingAlgorithm: MappingAlgorithm = (seed) => ({
  ...antdTheme.defaultAlgorithm(seed),
  ...adminSemanticColorTokens,
});

export function createAdminAntdTheme(mode: AdminThemeMode): ThemeConfig {
  return {
    algorithm: adminMappingAlgorithm,
    cssVar: {
      key: `cms-admin-${mode}`,
      prefix: 'cms-antd',
    },
    hashed: false,
    token: {
      ...adminSemanticColorTokens,
      colorBgBase: 'var(--cms-bg-canvas)',
      colorPrimary: 'var(--cms-primary)',
      colorSuccess: 'var(--cms-success)',
      colorWarning: 'var(--cms-warning)',
      colorError: 'var(--cms-danger)',
      colorInfo: 'var(--cms-info)',
      colorTextBase: 'var(--cms-text-primary)',
      colorLink: 'var(--cms-info)',
      fontFamily: 'var(--cms-font-sans)',
      fontFamilyCode: 'var(--cms-font-mono)',
      fontSize: 14,
      borderRadius: 9,
      controlHeight: 39,
      zIndexPopupBase: 1000,
      motion: false,
    },
    components: {
      Table: {
        headerBg: 'var(--cms-bg-surface-muted)',
        headerColor: 'var(--cms-text-muted)',
        rowHoverBg: 'var(--cms-bg-surface-hover)',
        borderColor: 'var(--cms-border-default)',
      },
    },
  };
}
